### PR TITLE
added magnet link extraction

### LINKED ISSUE #2: Sumotorrents not starting downloads
Added plugin and search works, but cant download anything double clicking- results from sumotorrent doesnt start up, doesnt show up in qbitorrent.

### PR DESCRIPTION
**Pull request by hannsen**
closes #2 

This will create some http load and take longer, 
but the download button will work again for most of the torrents.

One could speed this up with parallel requests, but at this point I already spent too much time on this.
If someone is interested to do it parallel they can look at my search plugin repo, I do it in some plugins with threading.

Oh I forgot to mention, I limited the results to 20 so it does not create mad amounts of http load

To make sure that all the links will work, one has to request the description page and parse for the magnet link. I tried this first, but it failed for adult links, since you have to press the 'I am 18' button

### CODE REVIEW

**Comment by hannsen** [comment]
I was just thinking, the ultimate solution would be to only parse for the magnet link once the user clicks download.

As far as I know you can only do that if you define a download_torrent() in your class. With that you can download torrent files on your own with a given input url. Sadly qbit does not accept it when you just return a magnet link there instead of a torrent file. So that needs a pull request to the main qbit repo

**Comment by Pireo** [comment]
https://github.com/qbittorrent/search-plugins/blob/master/nova/engines/torrentz.py

perhaps this can help you, since torrentz does not have any download torrent option and relies on magnet links.

**Comment by hannsen** [comment]
Not really, this plugin extracts the torrent hashes from the main search page and makes a magnet link out of it

**Comment by hannsen** [comment]
here is the code where qbit adds magnets from the search page directly.
https://github.com/qbittorrent/qBittorrent/blob/master/src/gui/search/searchtab.cpp#L252

somewhere in the else clause it needs to accept magnet links as well

**Comment by hannsen** [comment]
after further investigation i found a better way

**Pull request closed without merging**
